version: '3.7' # specify docker-compose version

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: splitter
      POSTGRES_USER: user
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./data/pg-initdb.d:/docker-entrypoint-initdb.d