version: '3.7' # specify docker-compose version

services:
  api-test:
    build:
      context: .
      dockerfile: src/test/Dockerfile.test
    command: [ "sh", "-c", "gradle --no-daemon test --fail-fast --console plain --stacktrace" ]
    ports:
      - "8080:8080"
  postgres-test:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: splitter
      POSTGRES_USER: user
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./data/pg-initdb.d:/docker-entrypoint-initdb.d